# Generated by Django 4.2.6 on 2023-10-31 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pril', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateField(auto_now_add=True, verbose_name='дата добавления')),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Планограмма',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['date_snat'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
